name: window_paint
description: Paint over another widget.
version: 0.0.1
homepage: https://github.com/Allvis-AS/window_paint
repository: https://github.com/Allvis-AS/window_paint
issue_tracker: https://github.com/Allvis-AS/window_paint/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
