name: window_paint
description: Paint over another widget.
version: 0.1.0-nullsafety.0
homepage: https://github.com/Allvis-AS/window_paint
repository: https://github.com/Allvis-AS/window_paint
issue_tracker: https://github.com/Allvis-AS/window_paint/issues

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
