name: window_paint
description: WindowPaint lets you pan, zoom and paint over any other widget. It uses the new InteractiveViewer together with a CustomPainter, giving you the bare minimum to get you started.
version: 0.1.0-nullsafety.2
homepage: https://github.com/Allvis-AS/window_paint
repository: https://github.com/Allvis-AS/window_paint
issue_tracker: https://github.com/Allvis-AS/window_paint/issues

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0-nullsafety.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
